# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-btvol

# >> macros
# << macros

Summary:    BT device Volume Control
Version:    1.1
Release:    1
Group:      Qt/Qt
License:    GPL3
URL:        https://github.com/fridlmue/harbour-btvol
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-btvol.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   kf5bluezqt
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description
App to change internal volume of some BT devices

# This description section includes metadata for SailfishOS:Chum, see
# https://github.com/sailfishos-chum/main/blob/main/Metadata.md
%if 0%{?_chum}
Title: BtVol
Type: desktop-application
DeveloperName: fridlmue
Categories:
 - Utility
Custom:
  Repo: https://github.com/fridlmue/harbour-btvol
PackageIcon: https://github.com/fridlmue/harbour-btvol/raw/main/icons/172x172/harbour-btvol.png
Screenshots:
 - https://github.com/fridlmue/harbour-btvol/raw/main/screenshots/about.png
 - https://github.com/fridlmue/harbour-btvol/raw/main/screenshots/dev_list.png
Links:
  Homepage: https://github.com/fridlmue/harbour-btvol
  Help: https://github.com/fridlmue/harbour-btvol/discussions
  Bugtracker: https://github.com/fridlmue/harbour-btvol/issues
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
